// Generated by packages/catalog/scripts/generate-baseline.mjs from docs/PROVIDERS.md.
// Do not edit by hand. Run `pnpm --filter @eyeball/catalog generate` instead.

import { deepFreeze } from "./immutable.js";
import type { CapabilityCatalogEntry, ProviderCatalogEntry } from "./types.js";

const baseline = {
  capabilities: [
    {
      slug: "email",
      displayName: "Email",
      contractFocus: "Mailboxes, threads, drafts, search, and delivery",
      tools: [
        {
          name: "send_email",
          description:
            "Send a new message with recipients, content, and optional attachments.",
        },
        {
          name: "list_emails",
          description:
            "List messages from a mailbox or folder with pagination and filters.",
        },
        {
          name: "get_email",
          description:
            "Retrieve one message, headers, body, and attachment metadata.",
        },
        {
          name: "reply_to_email",
          description: "Reply within an existing message or thread.",
        },
        {
          name: "create_draft",
          description: "Create an unsent draft message.",
        },
        {
          name: "search_emails",
          description:
            "Search mailbox content using provider-supported query filters.",
        },
        {
          name: "list_threads",
          description: "List conversation threads and their latest state.",
        },
        {
          name: "add_email_label",
          description:
            "Apply a label, category, or folder operation to a message.",
        },
      ],
    },
    {
      slug: "calendar_scheduling",
      displayName: "Calendar & Scheduling",
      contractFocus: "Calendars, events, availability, and booking links",
      tools: [
        {
          name: "list_calendars",
          description: "List calendars visible to the connected account.",
        },
        {
          name: "list_events",
          description:
            "List events in a time range with calendar and attendee filters.",
        },
        {
          name: "get_event",
          description: "Retrieve one event and its attendance state.",
        },
        {
          name: "create_event",
          description:
            "Create an event with attendees, recurrence, and conferencing data.",
        },
        {
          name: "update_event",
          description: "Update an existing event or recurrence instance.",
        },
        {
          name: "delete_event",
          description: "Delete or cancel an event.",
        },
        {
          name: "find_available_times",
          description:
            "Compute candidate time slots from free/busy information.",
        },
        {
          name: "create_scheduling_link",
          description: "Create or retrieve a bookable scheduling link.",
        },
        {
          name: "respond_to_event",
          description: "Accept, tentatively accept, or decline an invitation.",
        },
      ],
    },
    {
      slug: "messaging_chat",
      displayName: "Messaging & Chat",
      contractFocus: "Channels, messages, replies, reactions, and members",
      tools: [
        {
          name: "send_message",
          description:
            "Send a message to a channel, room, group, or direct recipient.",
        },
        {
          name: "list_channels",
          description:
            "List channels, rooms, groups, or chats visible to the connection.",
        },
        {
          name: "list_messages",
          description:
            "List recent messages in a conversation with pagination.",
        },
        {
          name: "get_message",
          description: "Retrieve one message and its metadata.",
        },
        {
          name: "reply_to_message",
          description: "Reply in a thread or to a specific message.",
        },
        {
          name: "add_reaction",
          description: "Add an emoji or supported reaction to a message.",
        },
        {
          name: "create_channel",
          description:
            "Create a channel, room, or group where the provider permits it.",
        },
        {
          name: "list_members",
          description: "List members of a workspace, channel, or chat.",
        },
      ],
    },
    {
      slug: "voice_telephony",
      displayName: "Voice & Telephony",
      contractFocus: "PSTN/WebRTC calls, rooms, media, speech, and pipelines",
      tools: [
        {
          name: "start_call",
          description:
            "Start an outbound PSTN, SIP, or provider-hosted call and return an execution ID.",
        },
        {
          name: "get_call",
          description:
            "Retrieve call state, participants, timing, and provider identifiers.",
        },
        {
          name: "list_calls",
          description:
            "List calls using status, participant, and time filters.",
        },
        {
          name: "end_call",
          description: "End an active call.",
        },
        {
          name: "transfer_call",
          description:
            "Transfer or bridge an active call to another destination.",
        },
        {
          name: "send_dtmf",
          description: "Send DTMF digits to an active call leg.",
        },
        {
          name: "create_room",
          description:
            "Create a realtime audio/video room with access metadata.",
        },
        {
          name: "join_room",
          description:
            "Create participant credentials or join instructions for a room.",
        },
        {
          name: "synthesize_speech",
          description:
            "Convert text to speech using a selected voice and audio format.",
        },
        {
          name: "transcribe_audio",
          description: "Convert audio or a live audio source into text.",
        },
        {
          name: "start_voice_pipeline",
          description:
            "Start a composed transport, speech, model, and tool pipeline.",
        },
        {
          name: "get_voice_pipeline",
          description: "Retrieve pipeline state, events, and terminal outcome.",
        },
      ],
    },
    {
      slug: "sms",
      displayName: "SMS",
      contractFocus: "SMS/MMS delivery, status, and verification",
      tools: [
        {
          name: "send_sms",
          description:
            "Send a plain-text message to one or more phone numbers.",
        },
        {
          name: "get_sms",
          description: "Retrieve one outbound or inbound message record.",
        },
        {
          name: "list_sms",
          description:
            "List message records using recipient, sender, status, and time filters.",
        },
        {
          name: "send_mms",
          description: "Send a message with supported media attachments.",
        },
        {
          name: "get_delivery_status",
          description:
            "Retrieve normalized carrier and provider delivery state.",
        },
        {
          name: "send_verification_code",
          description: "Start a provider-managed one-time-code verification.",
        },
        {
          name: "check_verification_code",
          description: "Verify a submitted one-time code.",
        },
      ],
    },
    {
      slug: "crm",
      displayName: "CRM",
      contractFocus: "Contacts, companies, deals, activities, and notes",
      tools: [
        {
          name: "create_contact",
          description: "Create a person/contact record.",
        },
        {
          name: "get_contact",
          description: "Retrieve one contact by provider ID.",
        },
        {
          name: "search_contacts",
          description:
            "Search contacts by identity, property, or provider query.",
        },
        {
          name: "update_contact",
          description: "Update fields on an existing contact.",
        },
        {
          name: "create_company",
          description: "Create an account, organization, or company record.",
        },
        {
          name: "update_company",
          description: "Update an account, organization, or company record.",
        },
        {
          name: "create_deal",
          description: "Create an opportunity or deal in a pipeline.",
        },
        {
          name: "update_deal",
          description: "Update deal fields, stage, amount, or owner.",
        },
        {
          name: "list_activities",
          description:
            "List calls, meetings, tasks, or timeline activities for a record.",
        },
        {
          name: "add_note",
          description: "Add a note to a contact, company, or deal.",
        },
      ],
    },
    {
      slug: "erp_accounting",
      displayName: "ERP & Accounting",
      contractFocus: "Customers, invoices, bills, ledgers, and payments",
      tools: [
        {
          name: "list_customers",
          description:
            "List customer or partner records with pagination and filters.",
        },
        {
          name: "create_customer",
          description: "Create a customer or business partner.",
        },
        {
          name: "list_invoices",
          description: "List sales invoices by state, customer, or date.",
        },
        {
          name: "get_invoice",
          description: "Retrieve an invoice, line items, totals, and status.",
        },
        {
          name: "create_invoice",
          description:
            "Create a sales invoice with line items, tax, and terms.",
        },
        {
          name: "send_invoice",
          description: "Issue or email an invoice using the provider workflow.",
        },
        {
          name: "record_payment",
          description: "Record or apply a payment to an invoice or account.",
        },
        {
          name: "list_bills",
          description: "List vendor bills or accounts-payable documents.",
        },
        {
          name: "create_bill",
          description: "Create a vendor bill with line items and due terms.",
        },
        {
          name: "list_accounts",
          description: "List chart-of-account or ledger accounts.",
        },
        {
          name: "create_journal_entry",
          description: "Create a balanced general-ledger journal entry.",
        },
        {
          name: "search_erp_records",
          description: "Search a supported ERP model or accounting object.",
        },
      ],
    },
    {
      slug: "social_media_data",
      displayName: "Social Media Data",
      contractFocus:
        "Public profiles, content, comments, discovery, and transcripts",
      tools: [
        {
          name: "get_profile",
          description:
            "Retrieve a public creator or user profile and visible metrics.",
        },
        {
          name: "get_posts",
          description: "List public posts or media for a profile or community.",
        },
        {
          name: "get_post",
          description: "Retrieve one post, video, clip, short, or media item.",
        },
        {
          name: "get_comments",
          description:
            "List public comments and supported replies for a content item.",
        },
        {
          name: "search_posts",
          description:
            "Search public content using a platform-supported query.",
        },
        {
          name: "search_creators",
          description:
            "Search or discover creators where the platform adapter supports it.",
        },
        {
          name: "get_transcript",
          description:
            "Retrieve or derive the transcript for a supported public video/audio post.",
        },
        {
          name: "get_channel",
          description:
            "Retrieve a channel, company, community, or subreddit entity.",
        },
        {
          name: "get_channel_videos",
          description: "List videos, shorts, streams, or clips from a channel.",
        },
        {
          name: "get_live_content",
          description: "Retrieve current or scheduled live-content metadata.",
        },
        {
          name: "get_audience_metrics",
          description:
            "Retrieve public or explicitly supported audience/engagement metrics.",
        },
        {
          name: "get_trending_content",
          description:
            "Retrieve a documented trending feed, hashtag, reel, or short surface.",
        },
      ],
    },
    {
      slug: "social_media_publishing",
      displayName: "Social Media Publishing",
      contractFocus:
        "Account-authorized publishing, scheduling, media, and metrics",
      tools: [
        {
          name: "create_post",
          description: "Publish a text or mixed-media post immediately.",
        },
        {
          name: "schedule_post",
          description: "Schedule a post for future publication.",
        },
        {
          name: "get_published_post",
          description:
            "Retrieve one published or scheduled post and its state.",
        },
        {
          name: "delete_post",
          description: "Delete a post where the provider API permits it.",
        },
        {
          name: "upload_media",
          description: "Upload media for later attachment or publishing.",
        },
        {
          name: "publish_video",
          description:
            "Publish a video, reel, short, or equivalent media item.",
        },
        {
          name: "publish_story",
          description: "Publish an ephemeral story where supported.",
        },
        {
          name: "get_post_metrics",
          description:
            "Retrieve provider-authorized reach and engagement metrics.",
        },
        {
          name: "list_social_accounts",
          description:
            "List pages, channels, organizations, or profiles available to publish.",
        },
      ],
    },
    {
      slug: "file_storage_docs",
      displayName: "File Storage & Docs",
      contractFocus:
        "Files, folders, sharing, document export, and object storage",
      tools: [
        {
          name: "list_files",
          description: "List files and folders within a location.",
        },
        {
          name: "get_file",
          description:
            "Retrieve file metadata and a content/download reference.",
        },
        {
          name: "search_files",
          description:
            "Search file names, metadata, or provider-indexed content.",
        },
        {
          name: "upload_file",
          description: "Upload a new file or object.",
        },
        {
          name: "download_file",
          description:
            "Download file content through the executor's binary transport.",
        },
        {
          name: "move_file",
          description: "Move or rename a file or object.",
        },
        {
          name: "delete_file",
          description: "Delete or trash a file or object.",
        },
        {
          name: "create_folder",
          description: "Create a folder, prefix, or directory-like container.",
        },
        {
          name: "share_file",
          description: "Create or update access permissions or a share link.",
        },
        {
          name: "export_document",
          description:
            "Export a native document to a requested supported format.",
        },
      ],
    },
    {
      slug: "spreadsheets_databases",
      displayName: "Spreadsheets & Databases",
      contractFocus: "Rows, ranges, records, tables, and queries",
      tools: [
        {
          name: "list_rows",
          description:
            "List rows or records from a sheet, table, or view with pagination and filters.",
        },
        {
          name: "get_row",
          description: "Retrieve one row or record by provider identifier.",
        },
        {
          name: "create_row",
          description: "Create a row or record with field values.",
        },
        {
          name: "update_row",
          description: "Update fields or cells on an existing row or record.",
        },
        {
          name: "delete_row",
          description: "Delete one row or record.",
        },
        {
          name: "search_rows",
          description:
            "Search or filter rows using provider-supported expressions.",
        },
        {
          name: "append_row",
          description: "Append a row to the end of a sheet or table.",
        },
        {
          name: "get_range",
          description: "Read a rectangular spreadsheet range and its values.",
        },
        {
          name: "update_range",
          description: "Write values to a rectangular spreadsheet range.",
        },
        {
          name: "list_tables",
          description:
            "List worksheets, tables, collections, or database views.",
        },
        {
          name: "run_query",
          description:
            "Execute a provider-supported SQL or query-language statement and return tabular results.",
        },
      ],
    },
    {
      slug: "project_management_dev_tools",
      displayName: "Project Management & Dev Tools",
      contractFocus:
        "Projects, tasks, issues, code review, builds, and deploys",
      tools: [
        {
          name: "list_projects",
          description:
            "List projects, repositories, boards, or workspaces visible to the connection.",
        },
        {
          name: "create_issue",
          description:
            "Create an issue, work item, or defect with title, body, and ownership metadata.",
        },
        {
          name: "get_issue",
          description: "Retrieve one issue or work item and its current state.",
        },
        {
          name: "list_issues",
          description:
            "List issues or work items using project, assignee, state, and label filters.",
        },
        {
          name: "update_issue",
          description:
            "Update issue fields, state, assignment, labels, or priority.",
        },
        {
          name: "add_comment",
          description:
            "Add a comment or discussion update to an issue or task.",
        },
        {
          name: "create_task",
          description: "Create a task, card, or to-do in a project container.",
        },
        {
          name: "get_task",
          description: "Retrieve one task, card, or to-do and its metadata.",
        },
        {
          name: "update_task",
          description:
            "Update task fields, completion state, dates, or assignment.",
        },
        {
          name: "get_pull_request",
          description:
            "Retrieve a pull or merge request, review state, and change metadata.",
        },
        {
          name: "create_pull_request_comment",
          description:
            "Add a general or provider-supported review comment to a pull or merge request.",
        },
        {
          name: "list_commits",
          description:
            "List repository commits using branch, author, or time filters.",
        },
        {
          name: "get_build",
          description:
            "Retrieve a CI build or pipeline run and its jobs, status, and result.",
        },
        {
          name: "get_deployment",
          description:
            "Retrieve a deployment or release and its environment status.",
        },
      ],
    },
    {
      slug: "payments_billing",
      displayName: "Payments & Billing",
      contractFocus:
        "Payments, refunds, invoices, subscriptions, and transactions",
      tools: [
        {
          name: "create_payment_link",
          description:
            "Create a hosted link or checkout for collecting a payment.",
        },
        {
          name: "get_payment",
          description:
            "Retrieve one payment, charge, order, or transaction and its status.",
        },
        {
          name: "list_payments",
          description:
            "List payments or transactions using customer, status, and time filters.",
        },
        {
          name: "create_refund",
          description: "Refund all or part of a captured payment.",
        },
        {
          name: "get_customer",
          description:
            "Retrieve one billing customer and its payment metadata.",
        },
        {
          name: "create_customer",
          description: "Create a billing customer.",
        },
        {
          name: "list_subscriptions",
          description:
            "List subscriptions using customer, product, or status filters.",
        },
        {
          name: "cancel_subscription",
          description:
            "Cancel a subscription immediately or at the end of its billing period.",
        },
        {
          name: "create_invoice",
          description:
            "Create a billing invoice with line items and collection settings.",
        },
        {
          name: "get_invoice",
          description:
            "Retrieve one billing invoice, totals, due state, and hosted references.",
        },
      ],
    },
    {
      slug: "ecommerce",
      displayName: "E-commerce",
      contractFocus: "Catalog, orders, inventory, fulfillment, and customers",
      tools: [
        {
          name: "list_products",
          description:
            "List products or catalog items using collection, status, and inventory filters.",
        },
        {
          name: "get_product",
          description:
            "Retrieve one product, variants, pricing, and inventory metadata.",
        },
        {
          name: "create_product",
          description: "Create a product and its initial variants or options.",
        },
        {
          name: "update_product",
          description:
            "Update product content, variants, pricing, or publication state.",
        },
        {
          name: "update_inventory",
          description: "Set or adjust inventory for a variant at a location.",
        },
        {
          name: "list_orders",
          description:
            "List orders using customer, fulfillment, payment, and time filters.",
        },
        {
          name: "get_order",
          description:
            "Retrieve one order, line items, customer, totals, and fulfillment state.",
        },
        {
          name: "update_order",
          description:
            "Update provider-supported order fields, status, or metadata.",
        },
        {
          name: "create_fulfillment",
          description:
            "Create a fulfillment or shipment with items and tracking data.",
        },
        {
          name: "list_customers",
          description: "List store customers using identity and time filters.",
        },
      ],
    },
    {
      slug: "customer_support",
      displayName: "Customer Support",
      contractFocus: "Tickets, conversations, assignment, and replies",
      tools: [
        {
          name: "create_ticket",
          description:
            "Create a support ticket with requester, subject, content, and priority.",
        },
        {
          name: "get_ticket",
          description:
            "Retrieve one ticket, requester, status, assignment, and custom fields.",
        },
        {
          name: "list_tickets",
          description:
            "List tickets using requester, assignee, status, priority, and time filters.",
        },
        {
          name: "update_ticket",
          description:
            "Update ticket status, priority, tags, fields, or assignment.",
        },
        {
          name: "add_ticket_reply",
          description: "Add a public reply or internal note to a ticket.",
        },
        {
          name: "assign_ticket",
          description: "Assign a ticket to an agent, team, or group.",
        },
        {
          name: "list_conversations",
          description:
            "List inbox conversations using state, assignee, and time filters.",
        },
        {
          name: "get_conversation",
          description: "Retrieve one conversation and its message history.",
        },
        {
          name: "send_conversation_reply",
          description:
            "Reply to an inbox conversation as the connected workspace.",
        },
      ],
    },
    {
      slug: "web_search_scraping",
      displayName: "Web Search & Scraping",
      contractFocus:
        "Search, rendered pages, crawls, extraction, and site maps",
      tools: [
        {
          name: "web_search",
          description:
            "Search the public web and return ranked results with titles, URLs, and snippets.",
        },
        {
          name: "get_page_content",
          description:
            "Fetch one page and return normalized text, Markdown, or supported HTML.",
        },
        {
          name: "crawl_site",
          description:
            "Crawl a bounded site or URL set and return discovered page content.",
        },
        {
          name: "extract_structured_data",
          description:
            "Extract schema-constrained structured data from one or more pages.",
        },
        {
          name: "get_sitemap",
          description: "Discover or retrieve a site's sitemap URLs.",
        },
        {
          name: "take_screenshot",
          description:
            "Render a page and return a screenshot at requested viewport settings.",
        },
      ],
    },
    {
      slug: "hr_recruiting",
      displayName: "HR & Recruiting",
      contractFocus: "Employees, candidates, jobs, and leave",
      tools: [
        {
          name: "list_employees",
          description:
            "List employee records using team, location, status, and employment filters.",
        },
        {
          name: "get_employee",
          description:
            "Retrieve one employee's profile, role, organization, and employment metadata.",
        },
        {
          name: "create_candidate",
          description:
            "Create a candidate or application for a recruiting job.",
        },
        {
          name: "get_candidate",
          description:
            "Retrieve one candidate, applications, stage, and recruiting activity.",
        },
        {
          name: "list_candidates",
          description:
            "List candidates using job, stage, owner, and time filters.",
        },
        {
          name: "update_candidate_stage",
          description:
            "Move a candidate or application to another recruiting stage.",
        },
        {
          name: "list_jobs",
          description:
            "List recruiting jobs or openings and their publication state.",
        },
        {
          name: "create_time_off_request",
          description: "Create a leave or time-off request for an employee.",
        },
      ],
    },
    {
      slug: "marketing_ads",
      displayName: "Marketing & Ads",
      contractFocus: "Campaigns, audiences, sends, ads, and performance",
      tools: [
        {
          name: "add_contact_to_list",
          description:
            "Add or update a contact in a mailing list, audience, or segment.",
        },
        {
          name: "create_campaign",
          description: "Create an email, newsletter, or advertising campaign.",
        },
        {
          name: "send_campaign",
          description: "Send or publish a prepared campaign.",
        },
        {
          name: "get_campaign",
          description:
            "Retrieve one campaign, configuration, and delivery state.",
        },
        {
          name: "get_campaign_stats",
          description:
            "Retrieve normalized delivery, engagement, conversion, or advertising metrics.",
        },
        {
          name: "create_audience",
          description: "Create a list, segment, or advertising audience.",
        },
        {
          name: "list_forms",
          description:
            "List lead-capture or subscription forms and their status.",
        },
      ],
    },
    {
      slug: "sign_forms",
      displayName: "Sign & Forms",
      contractFocus: "Signature requests, forms, and responses",
      tools: [
        {
          name: "create_signature_request",
          description:
            "Create and send a document signature request to one or more signers.",
        },
        {
          name: "get_signature_request",
          description:
            "Retrieve one signature request, recipients, and completion state.",
        },
        {
          name: "list_signature_requests",
          description:
            "List signature requests using status, sender, recipient, and time filters.",
        },
        {
          name: "download_signed_document",
          description:
            "Download the completed signed document or evidence bundle.",
        },
        {
          name: "list_forms",
          description: "List forms visible to the connected account.",
        },
        {
          name: "list_form_responses",
          description:
            "List submitted responses for a form with pagination and time filters.",
        },
        {
          name: "get_form_response",
          description: "Retrieve one response and its normalized answers.",
        },
      ],
    },
    {
      slug: "ai_media_utilities",
      displayName: "AI/Media Utilities",
      contractFocus: "Text, image, audio, document, and media transformations",
      tools: [
        {
          name: "generate_image",
          description:
            "Generate an image from a text prompt and optional supported image inputs.",
        },
        {
          name: "describe_image",
          description:
            "Analyze an image and return a textual description or requested visual fields.",
        },
        {
          name: "remove_image_background",
          description:
            "Remove an image background and return a transparent or replacement-background asset.",
        },
        {
          name: "extract_text_from_document",
          description:
            "Extract machine-readable text from a scanned image or document using OCR.",
        },
        {
          name: "convert_document",
          description: "Convert a supported document between file formats.",
        },
        {
          name: "translate_text",
          description: "Translate text between supported languages.",
        },
        {
          name: "transcribe_audio",
          description:
            "Convert prerecorded audio or video into text with timing metadata.",
        },
        {
          name: "summarize_url",
          description: "Summarize content at a supported public URL.",
        },
      ],
    },
  ],
  providers: [
    {
      toolkit: {
        slug: "gmail",
        displayName: "Gmail",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "email",
          notes:
            "Full mailbox/thread launch target; service-account mode may be added as alternate auth.",
        },
      ],
    },
    {
      toolkit: {
        slug: "microsoft-outlook",
        displayName: "Microsoft Outlook / Graph Mail",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "email",
          notes: "Microsoft Graph mail, folders, drafts, replies, and search.",
        },
      ],
    },
    {
      toolkit: {
        slug: "smtp",
        displayName: "Generic SMTP",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "email",
          notes:
            "Send-only baseline; no mailbox listing, search, or thread operations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "sendgrid",
        displayName: "SendGrid",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "email",
          notes:
            "Transactional send and templates; delivery events arrive later through triggers.",
        },
      ],
    },
    {
      toolkit: {
        slug: "resend",
        displayName: "Resend",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "email",
          notes:
            "Transactional send and domain-backed delivery; no mailbox reads.",
        },
      ],
    },
    {
      toolkit: {
        slug: "mailgun",
        displayName: "Mailgun",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "email",
          notes:
            "Transactional send and stored-event lookup; no general mailbox model.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-calendar",
        displayName: "Google Calendar",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes:
            "Full event CRUD, attendees, recurrence, and free/busy launch target.",
        },
      ],
    },
    {
      toolkit: {
        slug: "microsoft-calendar",
        displayName: "Microsoft 365 Calendar",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes: "Microsoft Graph calendars, events, responses, and schedules.",
        },
      ],
    },
    {
      toolkit: {
        slug: "calendly",
        displayName: "Calendly",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes:
            "Event types, scheduling links, invitees, and scheduled-event reads.",
        },
      ],
    },
    {
      toolkit: {
        slug: "cal-com",
        displayName: "Cal.com",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes: "Booking links, availability, bookings, and cancellations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "savvycal",
        displayName: "SavvyCal",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes: "Scheduling links and event/attendee operations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "zoom",
        displayName: "Zoom",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes:
            "Meeting creation and management; not a general calendar store.",
        },
      ],
    },
    {
      toolkit: {
        slug: "acuity-scheduling",
        displayName: "Acuity Scheduling",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "calendar_scheduling",
          notes:
            "Appointment types, availability, appointments, and cancellations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "slack",
        displayName: "Slack",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "messaging_chat",
          notes: "Channels, DMs, threads, reactions, files, and member lookup.",
        },
      ],
    },
    {
      toolkit: {
        slug: "discord",
        displayName: "Discord",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "messaging_chat",
          notes:
            "Bot-token connection for guild channels, messages, threads, and reactions.",
        },
      ],
    },
    {
      toolkit: {
        slug: "telegram",
        displayName: "Telegram Bot",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "messaging_chat",
          notes: "Bot API chats, messages, media, edits, and replies.",
        },
      ],
    },
    {
      toolkit: {
        slug: "whatsapp-business",
        displayName: "WhatsApp Business Cloud",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "messaging_chat",
          notes:
            "Meta Cloud API templates, session messages, and media; distinct from Twilio WhatsApp.",
        },
      ],
    },
    {
      toolkit: {
        slug: "microsoft-teams",
        displayName: "Microsoft Teams",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "messaging_chat",
          notes:
            "Teams, channels, chats, messages, and member operations through Graph.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-chat",
        displayName: "Google Chat",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "messaging_chat",
          notes: "Spaces, messages, threads, and memberships.",
        },
      ],
    },
    {
      toolkit: {
        slug: "mattermost",
        displayName: "Mattermost",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "messaging_chat",
          notes: "Server URL plus token; channels, posts, threads, and users.",
        },
      ],
    },
    {
      toolkit: {
        slug: "rocket-chat",
        displayName: "Rocket.Chat",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "messaging_chat",
          notes: "Self-hosted URL plus personal/bot token; rooms and messages.",
        },
      ],
    },
    {
      toolkit: {
        slug: "line",
        displayName: "LINE Messaging API",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "messaging_chat",
          notes:
            "Channel access token; push/reply messages and audience operations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "twilio",
        displayName: "Twilio",
        source: "native",
        tier: "P0",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "voice_telephony",
          notes:
            "PSTN/SIP calls, call control, recordings, SMS, and WhatsApp using Account SID/Auth Token.",
        },
        {
          capability: "sms",
          notes:
            "SMS/MMS and Verify; shares the P0 Twilio connection with Voice & Telephony.",
        },
      ],
    },
    {
      toolkit: {
        slug: "livekit",
        displayName: "LiveKit",
        source: "native",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes:
            "Realtime rooms, WebRTC participants, tracks, SIP, and agent-session transport.",
        },
      ],
    },
    {
      toolkit: {
        slug: "pipecat",
        displayName: "Pipecat",
        source: "native",
        tier: "P0",
      },
      authClass: "none",
      memberships: [
        {
          capability: "voice_telephony",
          notes:
            "Open-source voice-agent pipeline runtime; provider credentials come from composed toolkits.",
        },
      ],
    },
    {
      toolkit: {
        slug: "elevenlabs",
        displayName: "ElevenLabs",
        source: "native",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes: "Low-latency TTS, configured voices, and streaming audio.",
        },
      ],
    },
    {
      toolkit: {
        slug: "deepgram",
        displayName: "Deepgram",
        source: "native",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes: "Streaming and prerecorded STT with transcript events.",
        },
      ],
    },
    {
      toolkit: {
        slug: "telnyx",
        displayName: "Telnyx",
        source: "native",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes: "PSTN/SIP calls, media streaming, SMS, and number operations.",
        },
        {
          capability: "sms",
          notes: "SMS/MMS and delivery status; shares the P1 voice provider.",
        },
      ],
    },
    {
      toolkit: {
        slug: "retell-ai",
        displayName: "Retell AI",
        source: "native",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes:
            "Hosted voice-agent calls and lifecycle; a future adapter must compile RFC 002 revisions without changing their portable contract.",
        },
      ],
    },
    {
      toolkit: {
        slug: "vapi",
        displayName: "Vapi",
        source: "native",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes:
            "Hosted voice-call orchestration; a future adapter must compile RFC 002 revisions without changing their portable contract.",
        },
      ],
    },
    {
      toolkit: {
        slug: "vonage",
        displayName: "Vonage",
        source: "native",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "voice_telephony",
          notes:
            "Voice API and SMS alternate; JWT signing data is stored in the api_key credential class.",
        },
        {
          capability: "sms",
          notes: "SMS and Verify alternate; shares the P2 voice provider.",
        },
      ],
    },
    {
      toolkit: {
        slug: "plivo",
        displayName: "Plivo",
        source: "native",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "voice_telephony",
          notes: "PSTN/SIP calls and SMS alternate using Auth ID/Auth Token.",
        },
        {
          capability: "sms",
          notes: "SMS/MMS alternate; shares the P2 voice provider.",
        },
      ],
    },
    {
      toolkit: {
        slug: "messagebird",
        displayName: "MessageBird / Bird",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sms",
          notes:
            "SMS and messaging API; normalize current Bird product naming behind stable slug.",
        },
      ],
    },
    {
      toolkit: {
        slug: "clicksend-sms",
        displayName: "ClickSend SMS",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sms",
          notes: "SMS/MMS send and delivery history.",
        },
      ],
    },
    {
      toolkit: {
        slug: "textmagic",
        displayName: "TextMagic",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "sms",
          notes: "Username/API-key pair, messaging, contacts, and status.",
        },
      ],
    },
    {
      toolkit: {
        slug: "aws-sns",
        displayName: "Amazon SNS",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sms",
          notes:
            "AWS access credentials for SMS publish; no conversational inbox abstraction.",
        },
      ],
    },
    {
      toolkit: {
        slug: "hubspot",
        displayName: "HubSpot",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes:
            "Launch CRM for contacts, companies, deals, owners, associations, and notes.",
        },
      ],
    },
    {
      toolkit: {
        slug: "salesforce",
        displayName: "Salesforce",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes:
            "Standard/custom objects and SOQL-backed search; canonical CRM mappings cover core objects.",
        },
      ],
    },
    {
      toolkit: {
        slug: "pipedrive",
        displayName: "Pipedrive",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes:
            "Persons, organizations, deals, activities, notes, and pipelines.",
        },
      ],
    },
    {
      toolkit: {
        slug: "zoho-crm",
        displayName: "Zoho CRM",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes:
            "Leads, contacts, accounts, deals, activities, and module records.",
        },
      ],
    },
    {
      toolkit: {
        slug: "attio",
        displayName: "Attio",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes: "Objects, records, lists, attributes, and notes.",
        },
      ],
    },
    {
      toolkit: {
        slug: "close",
        displayName: "Close",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "crm",
          notes: "Leads, contacts, opportunities, activities, and notes.",
        },
      ],
    },
    {
      toolkit: {
        slug: "dynamics-365",
        displayName: "Microsoft Dynamics 365 Sales",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes:
            "Dataverse-backed accounts, contacts, opportunities, and activities.",
        },
      ],
    },
    {
      toolkit: {
        slug: "freshsales",
        displayName: "Freshsales",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "crm",
          notes: "Contacts, accounts, deals, tasks, and notes.",
        },
      ],
    },
    {
      toolkit: {
        slug: "copper",
        displayName: "Copper",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes: "People, companies, opportunities, activities, and tasks.",
        },
      ],
    },
    {
      toolkit: {
        slug: "streak",
        displayName: "Streak",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "crm",
          notes: "Gmail-native pipelines, boxes, contacts, and tasks.",
        },
      ],
    },
    {
      toolkit: {
        slug: "odoo",
        displayName: "Odoo",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Contacts plus generic model search/create/update through XML-RPC; URL, database, username, and API key.",
        },
      ],
    },
    {
      toolkit: {
        slug: "quickbooks",
        displayName: "QuickBooks Online",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Customers, invoices, bills, payments, accounts, and journal entries.",
        },
      ],
    },
    {
      toolkit: {
        slug: "xero",
        displayName: "Xero",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Contacts, invoices, bills, payments, accounts, and tenant selection.",
        },
      ],
    },
    {
      toolkit: {
        slug: "zoho-books",
        displayName: "Zoho Books",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Organization-scoped contacts, invoices, bills, payments, and journals.",
        },
      ],
    },
    {
      toolkit: {
        slug: "sage-business-cloud",
        displayName: "Sage Business Cloud Accounting",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Contacts, sales invoices, purchase invoices, payments, and ledgers.",
        },
      ],
    },
    {
      toolkit: {
        slug: "freshbooks",
        displayName: "FreshBooks",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes: "Clients, invoices, expenses, payments, and time entries.",
        },
      ],
    },
    {
      toolkit: {
        slug: "netsuite",
        displayName: "Oracle NetSuite",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "SuiteTalk records; token-based OAuth 1 credential tuple is classified as api_key.",
        },
      ],
    },
    {
      toolkit: {
        slug: "sap-business-one",
        displayName: "SAP Business One",
        source: "native",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Service Layer business partners, documents, inventory, and journals; enterprise test environment required.",
        },
      ],
    },
    {
      toolkit: {
        slug: "oracle-fusion-cloud-erp",
        displayName: "Oracle Fusion Cloud ERP",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Receivables, payables, ledgers, and suppliers; enterprise instance variability.",
        },
      ],
    },
    {
      toolkit: {
        slug: "dynamics-365-business-central",
        displayName: "Microsoft Dynamics 365 Business Central",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Companies, customers, sales invoices, vendors, purchase invoices, and journals.",
        },
      ],
    },
    {
      toolkit: {
        slug: "wave-accounting",
        displayName: "Wave",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "erp_accounting",
          notes:
            "Businesses, customers, invoices, products, and money transactions.",
        },
      ],
    },
    {
      toolkit: {
        slug: "instagram-data",
        displayName: "Instagram via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: profile, posts/reels, post detail, comments, transcript, hashtag/profile search, and trending reels; comments are documented as less reliable.",
        },
      ],
    },
    {
      toolkit: {
        slug: "tiktok-data",
        displayName: "TikTok via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: profile, profile videos, video detail/comments, transcript, user search, popular creators, audience countries, live state, hashtags, and trending feed.",
        },
      ],
    },
    {
      toolkit: {
        slug: "youtube-data",
        displayName: "YouTube via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: channel, videos/shorts/lives/community posts, video detail/comments, transcript, search, playlists, and trending shorts.",
        },
      ],
    },
    {
      toolkit: {
        slug: "x-data",
        displayName: "Twitter/X via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: profile, user tweets, tweet detail, video-tweet transcript, community, and community tweets; no general comments or search promise.",
        },
      ],
    },
    {
      toolkit: {
        slug: "linkedin-data",
        displayName: "LinkedIn via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: public person profile/recent posts, company page/posts, public post search, post detail, and available video transcript.",
        },
      ],
    },
    {
      toolkit: {
        slug: "reddit-data",
        displayName: "Reddit via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: subreddit details/posts/search, sitewide post search, post comments, and Reddit-video transcript.",
        },
      ],
    },
    {
      toolkit: {
        slug: "twitch-data",
        displayName: "Twitch via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Confirmed: profile, user videos, user schedule, and clip detail; no comment, creator-search, or transcript promise.",
        },
      ],
    },
    {
      toolkit: {
        slug: "snapchat-data",
        displayName: "Snapchat via ScrapeCreators",
        source: "scrapecreators",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_data",
          notes:
            "Only public user profile is confirmed in the documented endpoint list; do not promise posts, stories, comments, search, or transcript until documented.",
        },
      ],
    },
    {
      toolkit: {
        slug: "facebook-pages",
        displayName: "Facebook Pages",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Page selection, feed posts, photos/videos, and page insights.",
        },
      ],
    },
    {
      toolkit: {
        slug: "instagram-for-business",
        displayName: "Instagram for Business",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Professional-account photos, carousels, reels, stories, and insights.",
        },
      ],
    },
    {
      toolkit: {
        slug: "linkedin-publishing",
        displayName: "LinkedIn Publishing",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Member/organization posts, articles/media, deletion, and authorized metrics.",
        },
      ],
    },
    {
      toolkit: {
        slug: "x-publishing",
        displayName: "Twitter/X Publishing",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Posts, replies, media, deletion, and account-authorized lookup subject to X API tier.",
        },
      ],
    },
    {
      toolkit: {
        slug: "youtube-publishing",
        displayName: "YouTube Publishing",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Video upload, metadata, playlists, and channel-authorized analytics.",
        },
      ],
    },
    {
      toolkit: {
        slug: "pinterest",
        displayName: "Pinterest",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes: "Boards, pins, media, and pin analytics.",
        },
      ],
    },
    {
      toolkit: {
        slug: "buffer",
        displayName: "Buffer",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes: "Cross-network profiles, drafts, queueing, and scheduling.",
        },
      ],
    },
    {
      toolkit: {
        slug: "typefully",
        displayName: "Typefully",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Drafting/scheduling for supported networks and publication status.",
        },
      ],
    },
    {
      toolkit: {
        slug: "tiktok-publishing",
        displayName: "TikTok Content Posting",
        source: "native",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Direct-post/upload APIs with app review; distinct from public-data scraping.",
        },
      ],
    },
    {
      toolkit: {
        slug: "hootsuite",
        displayName: "Hootsuite",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Cross-network scheduling and status where the upstream piece exposes it.",
        },
      ],
    },
    {
      toolkit: {
        slug: "mastodon",
        displayName: "Mastodon",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "social_media_publishing",
          notes:
            "Instance URL plus access token; statuses, media, replies, and deletion.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-drive",
        displayName: "Google Drive",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes:
            "Launch file provider for search, upload/download, folders, permissions, and Google-native export.",
        },
      ],
    },
    {
      toolkit: {
        slug: "dropbox",
        displayName: "Dropbox",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes: "Files, folders, search, moves, shared links, and revisions.",
        },
      ],
    },
    {
      toolkit: {
        slug: "onedrive",
        displayName: "Microsoft OneDrive",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes:
            "Microsoft Graph drives, items, upload/download, folders, and sharing.",
        },
      ],
    },
    {
      toolkit: {
        slug: "box",
        displayName: "Box",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes: "Files, folders, search, collaborations, and shared links.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-docs",
        displayName: "Google Docs",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes: "Create/read/edit document content and export through Drive.",
        },
      ],
    },
    {
      toolkit: {
        slug: "sharepoint",
        displayName: "Microsoft SharePoint",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes:
            "Sites, document libraries, drives, list-backed files, and permissions.",
        },
      ],
    },
    {
      toolkit: {
        slug: "amazon-s3",
        displayName: "Amazon S3",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "file_storage_docs",
          notes:
            "Buckets, objects, prefixes, copy/move, signed downloads, and metadata.",
        },
      ],
    },
    {
      toolkit: {
        slug: "cloudinary",
        displayName: "Cloudinary",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "file_storage_docs",
          notes:
            "Media upload, search, transformations, delivery URLs, and deletion.",
        },
      ],
    },
    {
      toolkit: {
        slug: "sftp",
        displayName: "SFTP",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "file_storage_docs",
          notes:
            "Host/user/password or SSH-key connection; files and directories.",
        },
      ],
    },
    {
      toolkit: {
        slug: "egnyte",
        displayName: "Egnyte",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "file_storage_docs",
          notes: "Enterprise files, folders, links, permissions, and search.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-sheets",
        displayName: "Google Sheets",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Launch spreadsheet target for worksheets, row search/append, and range reads/writes.",
        },
      ],
    },
    {
      toolkit: {
        slug: "airtable",
        displayName: "Airtable",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Bases, tables, views, record CRUD, and formula-backed filtering; no spreadsheet ranges.",
        },
      ],
    },
    {
      toolkit: {
        slug: "notion",
        displayName: "Notion",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Databases, data sources, pages, property updates, and filtered queries; also fits File Storage & Docs.",
        },
      ],
    },
    {
      toolkit: {
        slug: "microsoft-excel",
        displayName: "Microsoft Excel",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Microsoft Graph workbooks, worksheets, tables, ranges, and row writes.",
        },
      ],
    },
    {
      toolkit: {
        slug: "postgres",
        displayName: "PostgreSQL",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Host/database/user credentials for table discovery, parameterized SQL, and row operations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "mysql",
        displayName: "MySQL",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Host/database/user credentials for table discovery, parameterized SQL, and row operations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "supabase",
        displayName: "Supabase",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "PostgREST table CRUD and filters plus RPC calls exposed by the connected project.",
        },
      ],
    },
    {
      toolkit: {
        slug: "mongodb",
        displayName: "MongoDB",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Databases, collections, document CRUD, and document filters; maps documents to records, not ranges.",
        },
      ],
    },
    {
      toolkit: {
        slug: "smartsheet",
        displayName: "Smartsheet",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Sheets, rows, columns, cells, attachments, and row placement.",
        },
      ],
    },
    {
      toolkit: {
        slug: "baserow",
        displayName: "Baserow",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Databases, tables, fields, row CRUD, and filtering for cloud or self-hosted instances.",
        },
      ],
    },
    {
      toolkit: {
        slug: "nocodb",
        displayName: "NocoDB",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "spreadsheets_databases",
          notes:
            "Bases, tables, views, record CRUD, filtering, and pagination.",
        },
      ],
    },
    {
      toolkit: {
        slug: "github",
        displayName: "GitHub",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Repositories, issues, comments, pull requests, commits, Actions runs, and deployments.",
        },
      ],
    },
    {
      toolkit: {
        slug: "linear",
        displayName: "Linear",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Teams, projects, issues, comments, labels, cycles, states, and assignments.",
        },
      ],
    },
    {
      toolkit: {
        slug: "jira",
        displayName: "Jira Cloud",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Projects, issues, comments, fields, transitions, labels, and users.",
        },
      ],
    },
    {
      toolkit: {
        slug: "asana",
        displayName: "Asana",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Workspaces, projects, tasks, subtasks, comments, dates, and assignments.",
        },
      ],
    },
    {
      toolkit: {
        slug: "trello",
        displayName: "Trello",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Boards, lists, cards, checklists, comments, labels, and members.",
        },
      ],
    },
    {
      toolkit: {
        slug: "clickup",
        displayName: "ClickUp",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Workspaces, spaces, folders, lists, tasks, comments, and assignees.",
        },
      ],
    },
    {
      toolkit: {
        slug: "monday",
        displayName: "monday.com",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Workspaces, boards, groups, items, subitems, columns, and updates.",
        },
      ],
    },
    {
      toolkit: {
        slug: "gitlab",
        displayName: "GitLab",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Projects, issues, merge requests, notes, commits, pipelines, and deployments.",
        },
      ],
    },
    {
      toolkit: {
        slug: "todoist",
        displayName: "Todoist",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Projects, sections, tasks, comments, labels, and completion state.",
        },
      ],
    },
    {
      toolkit: {
        slug: "basecamp",
        displayName: "Basecamp",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Projects, to-do sets, to-dos, message boards, comments, and schedules.",
        },
      ],
    },
    {
      toolkit: {
        slug: "azure-devops",
        displayName: "Azure DevOps",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "project_management_dev_tools",
          notes:
            "Projects, work items, repositories, pull requests, commits, builds, and releases through a PAT.",
        },
      ],
    },
    {
      toolkit: {
        slug: "stripe",
        displayName: "Stripe",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "payments_billing",
          notes:
            "Payment Links, Payment Intents, charges, refunds, customers, subscriptions, and invoices.",
        },
      ],
    },
    {
      toolkit: {
        slug: "paypal",
        displayName: "PayPal",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "payments_billing",
          notes:
            "Orders, captures, refunds, customers, invoices, and subscription plans.",
        },
      ],
    },
    {
      toolkit: {
        slug: "square",
        displayName: "Square",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "payments_billing",
          notes:
            "Payments, refunds, customers, invoices, catalog references, and subscriptions.",
        },
      ],
    },
    {
      toolkit: {
        slug: "paddle",
        displayName: "Paddle",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "payments_billing",
          notes:
            "Customers, subscriptions, transactions, adjustments, invoices, and checkout links.",
        },
      ],
    },
    {
      toolkit: {
        slug: "lemon-squeezy",
        displayName: "Lemon Squeezy",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "payments_billing",
          notes:
            "Customers, orders, subscriptions, invoices, products, and checkout URLs.",
        },
      ],
    },
    {
      toolkit: {
        slug: "razorpay",
        displayName: "Razorpay",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "payments_billing",
          notes:
            "Payment links, payments, refunds, customers, subscriptions, and invoices using key ID/secret.",
        },
      ],
    },
    {
      toolkit: {
        slug: "shopify",
        displayName: "Shopify",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "ecommerce",
          notes:
            "Products, variants, inventory, customers, orders, fulfillments, and tracking through the Admin API.",
        },
      ],
    },
    {
      toolkit: {
        slug: "woocommerce",
        displayName: "WooCommerce",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "ecommerce",
          notes:
            "Products, variations, stock, customers, orders, notes, and refunds using consumer credentials.",
        },
      ],
    },
    {
      toolkit: {
        slug: "bigcommerce",
        displayName: "BigCommerce",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ecommerce",
          notes:
            "Catalog products, variants, inventory, customers, orders, and shipments.",
        },
      ],
    },
    {
      toolkit: {
        slug: "squarespace",
        displayName: "Squarespace Commerce",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ecommerce",
          notes:
            "Products, variants, inventory, orders, transactions, and fulfillment updates.",
        },
      ],
    },
    {
      toolkit: {
        slug: "etsy",
        displayName: "Etsy",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "ecommerce",
          notes:
            "Shop listings, listing inventory, receipts, transactions, and shipment tracking.",
        },
      ],
    },
    {
      toolkit: {
        slug: "magento",
        displayName: "Adobe Commerce / Magento",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ecommerce",
          notes:
            "Products, stock, customers, orders, invoices, shipments, and credit memos.",
        },
      ],
    },
    {
      toolkit: {
        slug: "zendesk",
        displayName: "Zendesk",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "customer_support",
          notes:
            "Tickets, users, organizations, comments, groups, assignment, tags, and custom fields.",
        },
      ],
    },
    {
      toolkit: {
        slug: "intercom",
        displayName: "Intercom",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "customer_support",
          notes:
            "Contacts, conversations, messages, notes, assignment, tags, and closure.",
        },
      ],
    },
    {
      toolkit: {
        slug: "freshdesk",
        displayName: "Freshdesk",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "customer_support",
          notes:
            "Tickets, contacts, agents, groups, replies, notes, status, and assignment.",
        },
      ],
    },
    {
      toolkit: {
        slug: "front",
        displayName: "Front",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "customer_support",
          notes:
            "Inboxes, conversations, messages, comments, teammates, tags, and assignment.",
        },
      ],
    },
    {
      toolkit: {
        slug: "help-scout",
        displayName: "Help Scout",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "customer_support",
          notes:
            "Mailboxes, conversations, threads, customers, users, tags, and assignment.",
        },
      ],
    },
    {
      toolkit: {
        slug: "gorgias",
        displayName: "Gorgias",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "basic",
      memberships: [
        {
          capability: "customer_support",
          notes:
            "Tickets, messages, customers, users, tags, and assignment using domain/user/API-key credentials.",
        },
      ],
    },
    {
      toolkit: {
        slug: "firecrawl",
        displayName: "Firecrawl",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "web_search_scraping",
          notes:
            "Page scrape, crawl, map/sitemap discovery, search, and schema-guided extraction.",
        },
      ],
    },
    {
      toolkit: {
        slug: "serper",
        displayName: "Serper",
        source: "activepieces-bridge",
        tier: "P0",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "web_search_scraping",
          notes:
            "Google-backed web, news, image, places, and shopping search results; no general crawler.",
        },
      ],
    },
    {
      toolkit: {
        slug: "serpapi",
        displayName: "SerpApi",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "web_search_scraping",
          notes:
            "Multi-engine search result pages and vertical results; no general crawler.",
        },
      ],
    },
    {
      toolkit: {
        slug: "tavily",
        displayName: "Tavily",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "web_search_scraping",
          notes:
            "Agent-oriented web search, result content extraction, and bounded site filtering.",
        },
      ],
    },
    {
      toolkit: {
        slug: "browserless",
        displayName: "Browserless",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "web_search_scraping",
          notes:
            "Browser-rendered page content, scripted extraction, PDFs, and screenshots.",
        },
      ],
    },
    {
      toolkit: {
        slug: "jina-reader",
        displayName: "Jina AI Reader",
        source: "native",
        tier: "P2",
      },
      authClass: "none",
      memberships: [
        {
          capability: "web_search_scraping",
          notes:
            "Public URL-to-Markdown page reads through the Reader endpoint; no authenticated-site or crawl promise.",
        },
      ],
    },
    {
      toolkit: {
        slug: "bamboohr",
        displayName: "BambooHR",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "hr_recruiting",
          notes:
            "Employee directory, employee fields, reports, time-off balances, and requests; no recruiting contract.",
        },
      ],
    },
    {
      toolkit: {
        slug: "greenhouse",
        displayName: "Greenhouse",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "hr_recruiting",
          notes:
            "Jobs, candidates, applications, stages, activities, and recruiter ownership through Harvest APIs.",
        },
      ],
    },
    {
      toolkit: {
        slug: "lever",
        displayName: "Lever",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "hr_recruiting",
          notes:
            "Postings, candidates, opportunities, applications, stages, notes, and owners.",
        },
      ],
    },
    {
      toolkit: {
        slug: "personio",
        displayName: "Personio",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "hr_recruiting",
          notes:
            "Employees, attributes, absences, recruiting jobs, candidates, and application phases.",
        },
      ],
    },
    {
      toolkit: {
        slug: "workable",
        displayName: "Workable",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "hr_recruiting",
          notes:
            "Jobs, candidates, profiles, pipeline stages, activities, and recruiting members.",
        },
      ],
    },
    {
      toolkit: {
        slug: "gusto",
        displayName: "Gusto",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "hr_recruiting",
          notes:
            "Companies, employees, contractors, onboarding fields, payroll metadata, and supported time-off policies.",
        },
      ],
    },
    {
      toolkit: {
        slug: "mailchimp",
        displayName: "Mailchimp",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Audiences, members, tags, segments, campaigns, sends, reports, and signup forms.",
        },
      ],
    },
    {
      toolkit: {
        slug: "klaviyo",
        displayName: "Klaviyo",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Profiles, lists, segments, events, campaigns, flows, and engagement metrics.",
        },
      ],
    },
    {
      toolkit: {
        slug: "brevo",
        displayName: "Brevo",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Contacts, lists, attributes, email campaigns, sends, reports, and forms.",
        },
      ],
    },
    {
      toolkit: {
        slug: "activecampaign",
        displayName: "ActiveCampaign",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Contacts, lists, tags, campaigns, automations, forms, and campaign reports.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-ads",
        displayName: "Google Ads",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Campaigns, ad groups, customer lists, conversions, budgets, and performance reports; no email sends.",
        },
      ],
    },
    {
      toolkit: {
        slug: "meta-ads",
        displayName: "Meta Ads",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Campaigns, ad sets, ads, custom audiences, creatives, and insights; no email sends.",
        },
      ],
    },
    {
      toolkit: {
        slug: "beehiiv",
        displayName: "beehiiv",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "marketing_ads",
          notes:
            "Publications, subscribers, segments, newsletter posts, sends, and publication analytics.",
        },
      ],
    },
    {
      toolkit: {
        slug: "docusign",
        displayName: "DocuSign",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Templates, envelopes, recipients, send/status operations, completed documents, and evidence.",
        },
      ],
    },
    {
      toolkit: {
        slug: "dropbox-sign",
        displayName: "Dropbox Sign",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Signature requests, templates, signers, status, reminders, and completed-file downloads.",
        },
      ],
    },
    {
      toolkit: {
        slug: "pandadoc",
        displayName: "PandaDoc",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Documents from templates, recipients, send/status operations, and completed PDFs.",
        },
      ],
    },
    {
      toolkit: {
        slug: "typeform",
        displayName: "Typeform",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Workspaces, forms, questions, responses, and response pagination; no signatures.",
        },
      ],
    },
    {
      toolkit: {
        slug: "google-forms",
        displayName: "Google Forms",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "oauth2",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Forms, question schemas, responses, and linked Google Sheet references; no signatures.",
        },
      ],
    },
    {
      toolkit: {
        slug: "jotform",
        displayName: "Jotform",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Forms, questions, submissions, files, and response filtering; no signatures.",
        },
      ],
    },
    {
      toolkit: {
        slug: "tally",
        displayName: "Tally",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "sign_forms",
          notes:
            "Forms, fields, submissions, and response payloads; no signatures.",
        },
      ],
    },
    {
      toolkit: {
        slug: "openai-images",
        displayName: "OpenAI Images",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ai_media_utilities",
          notes:
            "Image generation and image-input description; this image-scoped toolkit does not expose general chat operations.",
        },
      ],
    },
    {
      toolkit: {
        slug: "remove-bg",
        displayName: "remove.bg",
        source: "activepieces-bridge",
        tier: "P2",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ai_media_utilities",
          notes:
            "Automated background removal with transparent output and supported replacement backgrounds.",
        },
      ],
    },
    {
      toolkit: {
        slug: "pdf-co",
        displayName: "PDF.co",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ai_media_utilities",
          notes:
            "PDF/document conversion, OCR, text extraction, merge/split, and output-file URLs.",
        },
      ],
    },
    {
      toolkit: {
        slug: "deepl",
        displayName: "DeepL",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ai_media_utilities",
          notes:
            "Text translation, language detection, formality controls, and supported document translation.",
        },
      ],
    },
    {
      toolkit: {
        slug: "assemblyai",
        displayName: "AssemblyAI",
        source: "activepieces-bridge",
        tier: "P1",
      },
      authClass: "api_key",
      memberships: [
        {
          capability: "ai_media_utilities",
          notes:
            "Prerecorded audio/video transcription, timestamps, speakers, chapters, and summarization of supported media URLs.",
        },
      ],
    },
  ],
} as const;

export const CAPABILITY_CATALOG = deepFreeze(
  baseline.capabilities satisfies readonly CapabilityCatalogEntry[],
);

export const PROVIDER_CATALOG = deepFreeze(
  baseline.providers satisfies readonly ProviderCatalogEntry[],
);
