import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const defaultRepositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);
const generatedMarker = "DO NOT EDIT: generated by pnpm docs:sdk";

export interface ApiParameter {
  name: string;
  type: string;
  optional: boolean;
  description: string;
}

export interface ApiSignature {
  declaration: string;
  parameters: readonly ApiParameter[];
  returnType: string;
}

export interface ApiCallable {
  kind: "function";
  name: string;
  summary: string;
  signatures: readonly ApiSignature[];
  throws: readonly string[];
  examples: readonly string[];
}

export interface ApiProperty {
  name: string;
  type: string;
  optional: boolean;
  readonly: boolean;
  description: string;
}

export interface ApiClass {
  kind: "class";
  name: string;
  summary: string;
  constructors: readonly ApiSignature[];
  properties: readonly ApiProperty[];
  methods: readonly ApiCallable[];
}

export interface ApiType {
  kind: "interface" | "type";
  name: string;
  summary: string;
  declaration: string;
  properties: readonly ApiProperty[];
}

export interface ApiVariable {
  kind: "variable";
  name: string;
  summary: string;
  type: string;
}

export type ApiExport = ApiCallable | ApiClass | ApiType | ApiVariable;

export interface SdkApiModel {
  exports: readonly ApiExport[];
}

interface NavigationGroup {
  group: string;
  pages: (string | NavigationGroup)[];
}

interface DocsConfig {
  navigation: NavigationGroup[];
  [key: string]: unknown;
}

interface PageSpec {
  slug: string;
  title: string;
  description: string;
  exports: readonly string[];
}

export interface GeneratedSdkReference {
  checksum: string;
  pages: ReadonlyMap<string, string>;
  navigation: readonly string[];
  model: SdkApiModel;
}

export interface GenerateSdkDocsOptions {
  repositoryRoot?: string;
  generatedRoot?: string;
  docsConfigPath?: string;
  check?: boolean;
}

const pageSpecs: readonly PageSpec[] = [
  {
    slug: "client",
    title: "Client API",
    description:
      "Construct the TypeScript client and access its typed service namespaces.",
    exports: [
      "Eyeball",
      "EyeballOptions",
      "EyeballClock",
      "EyeballSleep",
      "JsonValue",
      "VERSION",
    ],
  },
  {
    slug: "tools",
    title: "Tools API",
    description:
      "Discover, convert, execute, and dispatch canonical tools from model tool calls.",
    exports: [
      "ToolsClient",
      "executeToolCalls",
      "SearchToolsOptions",
      "SearchToolsResult",
      "GetToolsOptions",
      "GetToolsResult",
      "EyeballToolFormat",
      "EyeballToolFormatMap",
      "ExecuteToolOptions",
      "RunToolOptions",
      "ExecuteToolCallsOptions",
      "AnthropicToolCall",
      "AnthropicToolResultBlock",
      "OpenAIFunctionToolCall",
      "OpenAICustomToolCall",
      "OpenAIToolCall",
      "OpenAIToolResultMessage",
      "QualifiedToolName",
      "ToolDefinition",
      "ToolNameMap",
    ],
  },
  {
    slug: "executions",
    title: "Executions API",
    description:
      "Read execution records, filter project history, and wait for terminal state.",
    exports: [
      "ExecutionsClient",
      "ListExecutionsOptions",
      "WaitForExecutionOptions",
      "ExecutionPage",
      "AsyncExecuteResponse",
      "ExecutionId",
      "ExecutionAttachmentSummary",
      "ExecutionMode",
      "ExecutionRecord",
      "ExecutionResult",
      "ExecutionSource",
      "ExecutionStatus",
    ],
  },
  {
    slug: "connections",
    title: "Connections API",
    description:
      "Create and administer user-scoped development connection records.",
    exports: [
      "ConnectionsClient",
      "CreateConnectionOptions",
      "ConnectedConnection",
      "ConnectionSummary",
      "ConnectionPage",
      "RevokedConnection",
      "ConnectionId",
    ],
  },
  {
    slug: "files",
    title: "Files API",
    description:
      "Stage attachment bytes and list or retrieve project-scoped file metadata.",
    exports: [
      "FilesClient",
      "ListFilesOptions",
      "UploadFileOptions",
      "FileId",
      "StagedFileMetadata",
      "StagedFilePage",
      "StagedFileReference",
    ],
  },
  {
    slug: "webhooks",
    title: "Webhooks API",
    description:
      "Manage signed webhook endpoints, delivery history, and signature verification.",
    exports: [
      "WebhooksClient",
      "createWebhookSignature",
      "verifyWebhookSignature",
      "CreateWebhookEndpointOptions",
      "UpdateWebhookEndpointOptions",
      "ListWebhookEndpointsOptions",
      "ListWebhookDeliveriesOptions",
      "CreatedWebhookEndpoint",
      "RotatedWebhookSecret",
      "VerifyWebhookSignatureOptions",
      "WebhookDelivery",
      "WebhookDeliveryAttempt",
      "WebhookDeliveryPage",
      "WebhookDeliveryStatus",
      "WebhookEndpoint",
      "WebhookEndpointPage",
      "VoiceObserverFailedWebhookData",
      "VoiceObserverFailedWebhookEvent",
      "VoiceObserverFailureOperation",
      "VoiceObserverFailureReason",
      "WebhookEvent",
      "WebhookEventType",
      "WebhookSubscriptionEventType",
    ],
  },
  {
    slug: "triggers-subscriptions",
    title: "Triggers and subscriptions API",
    description:
      "Discover canonical triggers and manage push or polling subscriptions.",
    exports: [
      "TriggersClient",
      "SubscriptionsClient",
      "GetTriggersOptions",
      "CreateSubscriptionOptions",
      "ListSubscriptionsOptions",
      "CreatedTriggerSubscription",
      "QualifiedTriggerName",
      "TriggerDefinition",
      "TriggerEventData",
      "TriggerSubscription",
      "TriggerSubscriptionId",
      "TriggerSubscriptionPage",
      "TriggerWebhookEvent",
    ],
  },
  {
    slug: "trigger-events",
    title: "Trigger events API",
    description:
      "Read redacted project trigger history and current delivery outcomes without provider payloads or credentials.",
    exports: [
      "TriggerEventsClient",
      "ListTriggerEventsOptions",
      "TriggerEventArrivalId",
      "TriggerEventDedupStatus",
      "TriggerEventDeliveryMode",
      "TriggerEventDeliveryStatus",
      "TriggerEventDeliveryTarget",
      "TriggerEventRecord",
      "TriggerEventPage",
      "createTriggerEventArrivalId",
      "isTriggerEventArrivalId",
    ],
  },
  {
    slug: "errors",
    title: "Errors API",
    description:
      "Handle normalized SDK failures with the public error class and taxonomy.",
    exports: ["EyeballError", "NormalizedToolError", "TOOL_ERROR_CODES"],
  },
];

const typeFormatFlags =
  ts.TypeFormatFlags.NoTruncation |
  ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope |
  ts.TypeFormatFlags.UseFullyQualifiedType;

function displayParts(
  value: readonly ts.SymbolDisplayPart[] | string | undefined,
): string {
  if (value === undefined) return "";
  return typeof value === "string"
    ? value
    : ts.displayPartsToString([...value]);
}

function documentation(
  value: ts.Symbol | ts.Signature,
  checker: ts.TypeChecker,
): string {
  return displayParts(value.getDocumentationComment(checker)).trim();
}

function tagTexts(
  value: ts.Symbol | ts.Signature,
  checker: ts.TypeChecker,
  name: string,
): string[] {
  return value
    .getJsDocTags(checker)
    .filter((tag) => tag.name === name)
    .map((tag) => displayParts(tag.text).trim())
    .filter((text) => text.length > 0);
}

function unique(values: readonly string[]): string[] {
  return [...new Set(values)];
}

function firstDeclaration(symbol: ts.Symbol): ts.Declaration {
  const declaration = symbol.valueDeclaration ?? symbol.declarations?.[0];
  if (declaration === undefined) {
    throw new Error(`Public export ${symbol.getName()} has no declaration.`);
  }
  return declaration;
}

function isOptionalParameter(symbol: ts.Symbol): boolean {
  if ((symbol.flags & ts.SymbolFlags.Optional) !== 0) return true;
  return (symbol.declarations ?? []).some(
    (declaration) =>
      ts.isParameter(declaration) &&
      (declaration.questionToken !== undefined ||
        declaration.initializer !== undefined),
  );
}

function signatureDeclaration(
  name: string,
  signature: ts.Signature,
  checker: ts.TypeChecker,
): string {
  const declaration = signature.getDeclaration();
  const typeParameters =
    declaration !== undefined && ts.isFunctionLike(declaration)
      ? declaration.typeParameters
          ?.map((parameter) => parameter.getText())
          .join(", ")
      : undefined;
  const parameters = signature.getParameters().map((parameter) => {
    const parameterDeclaration = firstDeclaration(parameter);
    const type = checker.getTypeOfSymbolAtLocation(
      parameter,
      parameterDeclaration,
    );
    const rest =
      ts.isParameter(parameterDeclaration) &&
      parameterDeclaration.dotDotDotToken !== undefined
        ? "..."
        : "";
    const optional = isOptionalParameter(parameter) ? "?" : "";
    return `${rest}${parameter.getName()}${optional}: ${checker.typeToString(
      type,
      parameterDeclaration,
      typeFormatFlags,
    )}`;
  });
  const returnType = checker.typeToString(
    signature.getReturnType(),
    declaration,
    typeFormatFlags,
  );
  return `${name}${typeParameters === undefined ? "" : `<${typeParameters}>`}(${parameters.join(", ")}): ${returnType}`;
}

function signatureModel(
  name: string,
  signature: ts.Signature,
  checker: ts.TypeChecker,
): ApiSignature {
  const declaration = signature.getDeclaration();
  const parameters = signature.getParameters().map((parameter) => {
    const parameterDeclaration = firstDeclaration(parameter);
    const parameterType = checker.getTypeOfSymbolAtLocation(
      parameter,
      parameterDeclaration,
    );
    return {
      name: parameter.getName(),
      type: checker.typeToString(
        parameterType,
        parameterDeclaration,
        typeFormatFlags,
      ),
      optional: isOptionalParameter(parameter),
      description: documentation(parameter, checker),
    };
  });
  return {
    declaration: signatureDeclaration(name, signature, checker),
    parameters,
    returnType: checker.typeToString(
      signature.getReturnType(),
      declaration,
      typeFormatFlags,
    ),
  };
}

function callableModel(
  symbol: ts.Symbol,
  checker: ts.TypeChecker,
): ApiCallable {
  const declaration = firstDeclaration(symbol);
  const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
  const extractedSignatures = type
    .getCallSignatures()
    .map((signature) => signatureModel(symbol.getName(), signature, checker));
  if (extractedSignatures.length === 0) {
    throw new Error(
      `Public callable ${symbol.getName()} has no call signature.`,
    );
  }
  const parameterDocs = new Map(
    extractedSignatures
      .flatMap((signature) => signature.parameters)
      .filter((parameter) => parameter.description.length > 0)
      .map((parameter) => [parameter.name, parameter.description]),
  );
  const signatures = extractedSignatures.map((signature) => ({
    ...signature,
    parameters: signature.parameters.map((parameter) => ({
      ...parameter,
      description:
        parameter.description || parameterDocs.get(parameter.name) || "",
    })),
  }));
  const signatureDocs = type.getCallSignatures();
  return {
    kind: "function",
    name: symbol.getName(),
    summary:
      documentation(symbol, checker) ||
      documentation(signatureDocs[0] as ts.Signature, checker),
    signatures,
    throws: unique([
      ...tagTexts(symbol, checker, "throws"),
      ...signatureDocs.flatMap((signature) =>
        tagTexts(signature, checker, "throws"),
      ),
    ]),
    examples: unique([
      ...tagTexts(symbol, checker, "example"),
      ...signatureDocs.flatMap((signature) =>
        tagTexts(signature, checker, "example"),
      ),
    ]),
  };
}

function hasModifier(
  declaration: ts.Declaration,
  kind: ts.SyntaxKind,
): boolean {
  return (
    ts.canHaveModifiers(declaration) &&
    ts.getModifiers(declaration)?.some((modifier) => modifier.kind === kind) ===
      true
  );
}

function publicProperty(symbol: ts.Symbol): boolean {
  if (symbol.getName().startsWith("#")) return false;
  return !(symbol.declarations ?? []).some((declaration) => {
    const name = (declaration as ts.NamedDeclaration).name;
    return (
      hasModifier(declaration, ts.SyntaxKind.PrivateKeyword) ||
      hasModifier(declaration, ts.SyntaxKind.ProtectedKeyword) ||
      (name !== undefined && ts.isPrivateIdentifier(name))
    );
  });
}

function propertyModel(
  symbol: ts.Symbol,
  checker: ts.TypeChecker,
): ApiProperty {
  const declaration = firstDeclaration(symbol);
  const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
  return {
    name: symbol.getName(),
    type: checker.typeToString(type, declaration, typeFormatFlags),
    optional: (symbol.flags & ts.SymbolFlags.Optional) !== 0,
    readonly: (symbol.declarations ?? []).some((item) =>
      hasModifier(item, ts.SyntaxKind.ReadonlyKeyword),
    ),
    description: documentation(symbol, checker),
  };
}

function constructorModels(
  symbol: ts.Symbol,
  checker: ts.TypeChecker,
): ApiSignature[] {
  if (symbol.getName() !== "Eyeball" && symbol.getName() !== "EyeballError") {
    return [];
  }
  const declaration = firstDeclaration(symbol);
  const staticType = checker.getTypeOfSymbolAtLocation(symbol, declaration);
  return staticType
    .getConstructSignatures()
    .map((signature) => signatureModel("constructor", signature, checker));
}

function classModel(symbol: ts.Symbol, checker: ts.TypeChecker): ApiClass {
  const instanceType = checker.getDeclaredTypeOfSymbol(symbol);
  const properties = instanceType
    .getProperties()
    .filter(publicProperty)
    .sort((left, right) => left.getName().localeCompare(right.getName()));
  const methods: ApiCallable[] = [];
  const values: ApiProperty[] = [];
  for (const property of properties) {
    const declaration = firstDeclaration(property);
    const type = checker.getTypeOfSymbolAtLocation(property, declaration);
    if (type.getCallSignatures().length > 0) {
      methods.push(callableModel(property, checker));
    } else {
      values.push(propertyModel(property, checker));
    }
  }
  return {
    kind: "class",
    name: symbol.getName(),
    summary: documentation(symbol, checker),
    constructors: constructorModels(symbol, checker),
    properties: values,
    methods,
  };
}

function typeModel(
  symbol: ts.Symbol,
  checker: ts.TypeChecker,
  kind: "interface" | "type",
): ApiType {
  const declaration = firstDeclaration(symbol);
  const properties =
    kind === "interface"
      ? checker
          .getDeclaredTypeOfSymbol(symbol)
          .getProperties()
          .filter(publicProperty)
          .sort((left, right) => left.getName().localeCompare(right.getName()))
          .map((property) => propertyModel(property, checker))
      : [];
  return {
    kind,
    name: symbol.getName(),
    summary: documentation(symbol, checker),
    declaration: declaration.getText(declaration.getSourceFile()),
    properties,
  };
}

function variableModel(
  symbol: ts.Symbol,
  checker: ts.TypeChecker,
): ApiVariable {
  const declaration = firstDeclaration(symbol);
  return {
    kind: "variable",
    name: symbol.getName(),
    summary: documentation(symbol, checker),
    type: checker.typeToString(
      checker.getTypeOfSymbolAtLocation(symbol, declaration),
      declaration,
      typeFormatFlags,
    ),
  };
}

function resolvedExport(symbol: ts.Symbol, checker: ts.TypeChecker): ts.Symbol {
  return (symbol.flags & ts.SymbolFlags.Alias) !== 0
    ? checker.getAliasedSymbol(symbol)
    : symbol;
}

function exportModel(exported: ts.Symbol, checker: ts.TypeChecker): ApiExport {
  const symbol = resolvedExport(exported, checker);
  const name = exported.getName();
  let model: ApiExport;
  if ((symbol.flags & ts.SymbolFlags.Class) !== 0) {
    model = classModel(symbol, checker);
  } else if ((symbol.flags & ts.SymbolFlags.Function) !== 0) {
    model = callableModel(symbol, checker);
  } else if ((symbol.flags & ts.SymbolFlags.Interface) !== 0) {
    model = typeModel(symbol, checker, "interface");
  } else if ((symbol.flags & ts.SymbolFlags.TypeAlias) !== 0) {
    model = typeModel(symbol, checker, "type");
  } else if ((symbol.flags & ts.SymbolFlags.Variable) !== 0) {
    model = variableModel(symbol, checker);
  } else {
    throw new Error(
      `Unsupported public SDK export ${name} with flags ${symbol.flags}.`,
    );
  }
  return model.name === name ? model : { ...model, name };
}

function parseSdkConfig(repositoryRoot: string): ts.ParsedCommandLine {
  const configPath = join(repositoryRoot, "packages", "sdk", "tsconfig.json");
  const loaded = ts.readConfigFile(configPath, ts.sys.readFile);
  if (loaded.error !== undefined) {
    throw new Error(
      ts.flattenDiagnosticMessageText(loaded.error.messageText, "\n"),
    );
  }
  return ts.parseJsonConfigFileContent(
    loaded.config,
    ts.sys,
    dirname(configPath),
    {},
    configPath,
  );
}

export function extractSdkApi(
  repositoryRoot = defaultRepositoryRoot,
): SdkApiModel {
  const parsed = parseSdkConfig(repositoryRoot);
  const program = ts.createProgram({
    rootNames: parsed.fileNames,
    options: {
      ...parsed.options,
      baseUrl: repositoryRoot,
      paths: {
        ...parsed.options.paths,
        "@eyeball/catalog": ["packages/catalog/src/index.ts"],
        "@eyeball/core": ["packages/core/src/index.ts"],
      },
    },
  });
  const entryPath = join(repositoryRoot, "packages", "sdk", "src", "index.ts");
  const source = program.getSourceFile(entryPath);
  if (source === undefined) {
    throw new Error(`TypeScript program did not load ${entryPath}.`);
  }
  const checker = program.getTypeChecker();
  const moduleSymbol = checker.getSymbolAtLocation(source);
  if (moduleSymbol === undefined) {
    throw new Error(
      `TypeScript could not resolve the SDK module ${entryPath}.`,
    );
  }
  const exports = checker
    .getExportsOfModule(moduleSymbol)
    .sort((left, right) => left.getName().localeCompare(right.getName()))
    .map((symbol) => exportModel(symbol, checker));
  return { exports };
}

function markdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function inlineCode(value: string): string {
  return `<code>${value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("|", "&#124;")
    .replaceAll("{", "&#123;")
    .replaceAll("}", "&#125;")
    .replaceAll("\n", " ")}</code>`;
}

function normalizedDoc(value: string): string {
  return value.replace(
    /\{@link\s+(?<name>[^}|\s]+)(?:\s*\|\s*[^}]+)?\}/gu,
    "`$<name>`",
  );
}

function runnableExample(value: string): string {
  const declarations: string[] = [];
  if (/\beyeball\./u.test(value)) {
    declarations.push(
      'import { Eyeball } from "@eyeball/sdk";',
      "",
      "const eyeball = new Eyeball({",
      "  apiKey: process.env.EYEBALL_API_KEY!,",
      "  baseUrl: process.env.EYEBALL_EXECUTOR_URL!,",
      "});",
    );
  }
  if (/\binvoiceBytes\b/u.test(value)) {
    declarations.push("", "const invoiceBytes = new Uint8Array();");
  }
  if (/\bexecution\.executionId\b/u.test(value)) {
    declarations.push(
      "",
      'const execution = { executionId: "exe_01JZ6WA0Q73ZQ5B51SRYB6M4Z8" };',
    );
  }
  return [...declarations, declarations.length === 0 ? "" : "", value.trim()]
    .join("\n")
    .trim();
}

function parameterTable(parameters: readonly ApiParameter[]): string {
  if (parameters.length === 0) return "This call has no parameters.";
  const rows = parameters
    .map(
      (parameter) =>
        `| \`${markdownCell(parameter.name)}\` | ${inlineCode(parameter.type)} | ${parameter.optional ? "No" : "Yes"} | ${markdownCell(parameter.description || "—")} |`,
    )
    .join("\n");
  return `| Parameter | Type | Required | Description |\n|---|---|---|---|\n${rows}`;
}

function propertyTable(properties: readonly ApiProperty[]): string {
  const rows = properties
    .map(
      (property) =>
        `| \`${markdownCell(property.name)}\` | ${inlineCode(property.type)} | ${property.optional ? "No" : "Yes"} | ${property.readonly ? "Yes" : "No"} | ${markdownCell(property.description || "—")} |`,
    )
    .join("\n");
  return `| Property | Type | Required | Readonly | Description |\n|---|---|---|---|---|\n${rows}`;
}

function renderSignature(
  signature: ApiSignature,
  index: number,
  count: number,
): string {
  const label = count > 1 ? `#### Overload ${index + 1}\n\n` : "";
  return `${label}\`\`\`ts no-check\n${signature.declaration}\n\`\`\`\n\n${parameterTable(signature.parameters)}\n\n**Returns:** ${inlineCode(signature.returnType)}`;
}

function renderCallable(callable: ApiCallable, heading = "###"): string {
  const signatures = callable.signatures
    .map((signature, index) =>
      renderSignature(signature, index, callable.signatures.length),
    )
    .join("\n\n");
  const throws =
    callable.throws.length === 0
      ? ""
      : `\n\n**Throws**\n\n${callable.throws.map((item) => `- ${normalizedDoc(item)}`).join("\n")}`;
  const examples = callable.examples
    .map(
      (example) =>
        `\n\n**Example**\n\n\`\`\`ts\n${runnableExample(example)}\n\`\`\``,
    )
    .join("");
  return `${heading} \`${callable.name}\`\n\n${normalizedDoc(callable.summary)}\n\n${signatures}${throws}${examples}`;
}

function renderClass(value: ApiClass): string {
  const constructors = value.constructors
    .map(
      (signature, index) =>
        `### Constructor\n\n${renderSignature(signature, index, value.constructors.length)}`,
    )
    .join("\n\n");
  const properties =
    value.properties.length === 0
      ? ""
      : `### Properties\n\n${propertyTable(value.properties)}`;
  const methods = value.methods
    .map((method) => renderCallable(method))
    .join("\n\n");
  return `## \`${value.name}\`\n\n${normalizedDoc(value.summary)}\n\n${[constructors, properties, methods].filter((section) => section.length > 0).join("\n\n")}`;
}

function renderType(value: ApiType): string {
  const properties =
    value.properties.length === 0
      ? ""
      : `\n\n${propertyTable(value.properties)}`;
  return `### \`${value.name}\`\n\n${normalizedDoc(value.summary)}\n\n\`\`\`ts no-check\n${value.declaration}\n\`\`\`${properties}`;
}

function renderVariable(value: ApiVariable): string {
  return `## \`${value.name}\`\n\n${normalizedDoc(value.summary)}\n\n\`\`\`ts no-check\nconst ${value.name}: ${value.type}\n\`\`\``;
}

function validatePageAssignments(model: SdkApiModel): void {
  const assignments = new Map<string, string>();
  for (const page of pageSpecs) {
    for (const name of page.exports) {
      const previous = assignments.get(name);
      if (previous !== undefined) {
        throw new Error(
          `SDK export ${name} is assigned to both ${previous} and ${page.slug}.`,
        );
      }
      assignments.set(name, page.slug);
    }
  }
  const actual = new Set(model.exports.map((item) => item.name));
  const missing = [...actual].filter((name) => !assignments.has(name)).sort();
  const stale = [...assignments.keys()]
    .filter((name) => !actual.has(name))
    .sort();
  if (missing.length > 0 || stale.length > 0) {
    throw new Error(
      `SDK reference page assignment drift.${
        missing.length === 0
          ? ""
          : ` Unassigned exports: ${missing.join(", ")}.`
      }${stale.length === 0 ? "" : ` Missing exports: ${stale.join(", ")}.`}`,
    );
  }
}

function validateDocumentation(model: SdkApiModel): void {
  const errors: string[] = [];
  for (const item of model.exports) {
    if (item.kind !== "class") continue;
    for (const method of item.methods) {
      if (method.summary.length === 0) {
        errors.push(`${item.name}.${method.name} is missing a TSDoc summary`);
      }
      if (item.name !== "EyeballError" && method.throws.length === 0) {
        errors.push(`${item.name}.${method.name} is missing @throws`);
      }
    }
  }
  for (const qualifiedName of [
    "ToolsClient.get",
    "ToolsClient.execute",
    "ToolsClient.run",
    "ExecutionsClient.wait",
    "FilesClient.upload",
    "FilesClient.list",
    "TriggerEventsClient.list",
    "WebhooksClient.create",
    "SubscriptionsClient.create",
  ]) {
    const [className, methodName] = qualifiedName.split(".");
    const owner = model.exports.find(
      (item): item is ApiClass =>
        item.kind === "class" && item.name === className,
    );
    const method = owner?.methods.find(
      (candidate) => candidate.name === methodName,
    );
    if (method === undefined || method.examples.length === 0) {
      errors.push(`${qualifiedName} is missing @example`);
    }
  }
  if (errors.length > 0) {
    throw new Error(`SDK TSDoc validation failed:\n- ${errors.join("\n- ")}`);
  }
}

function renderPage(
  spec: PageSpec,
  model: SdkApiModel,
  checksum: string,
): string {
  const byName = new Map(model.exports.map((item) => [item.name, item]));
  const members = spec.exports.map((name) => {
    const item = byName.get(name);
    if (item === undefined)
      throw new Error(`Missing extracted SDK export ${name}.`);
    return item;
  });
  const values = members.filter(
    (item) =>
      item.kind === "class" ||
      item.kind === "function" ||
      item.kind === "variable",
  );
  const types = members.filter(
    (item): item is ApiType =>
      item.kind === "interface" || item.kind === "type",
  );
  const valueSections = values
    .map((item) => {
      if (item.kind === "class") return renderClass(item);
      if (item.kind === "function") return renderCallable(item, "##");
      return renderVariable(item);
    })
    .join("\n\n");
  const typeSections =
    types.length === 0
      ? ""
      : `## Types\n\n${types.map(renderType).join("\n\n")}`;
  return `---
title: ${JSON.stringify(spec.title)}
description: ${JSON.stringify(spec.description)}
---

<!-- ${generatedMarker}; SDK checksum ${checksum}. -->

${spec.description}

${[valueSections, typeSections].filter((section) => section.length > 0).join("\n\n")}
`;
}

export function buildSdkReference(
  repositoryRoot = defaultRepositoryRoot,
): GeneratedSdkReference {
  const model = extractSdkApi(repositoryRoot);
  validatePageAssignments(model);
  validateDocumentation(model);
  const checksum = createHash("sha256")
    .update(JSON.stringify(model))
    .digest("hex")
    .slice(0, 16);
  const pages = new Map(
    pageSpecs.map((spec) => [
      `${spec.slug}.mdx`,
      renderPage(spec, model, checksum),
    ]),
  );
  return {
    checksum,
    pages,
    navigation: pageSpecs.map((spec) => `sdk/generated/${spec.slug}`),
    model,
  };
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return undefined;
    }
    throw error;
  }
}

async function assertOrWrite(
  path: string,
  content: string,
  check: boolean,
  repositoryRoot: string,
): Promise<void> {
  const previous = await readOptional(path);
  if (previous === content) return;
  if (check) {
    throw new Error(
      `${relative(repositoryRoot, path)} is stale; run pnpm docs:sdk.`,
    );
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function sdkNavigation(
  authoredPages: readonly string[],
  generatedPages: readonly string[],
): (string | NavigationGroup)[] {
  return [
    {
      group: "Guides",
      pages: [...authoredPages],
    },
    {
      group: "Generated API",
      pages: [...generatedPages],
    },
  ];
}

export async function generateSdkDocs(
  options: GenerateSdkDocsOptions = {},
): Promise<GeneratedSdkReference> {
  const repositoryRoot = options.repositoryRoot ?? defaultRepositoryRoot;
  const docsRoot = join(repositoryRoot, "docs-site");
  const generatedRoot =
    options.generatedRoot ?? join(docsRoot, "sdk", "generated");
  const docsConfigPath = options.docsConfigPath ?? join(docsRoot, "docs.json");
  const check = options.check ?? false;
  const reference = buildSdkReference(repositoryRoot);
  for (const [filename, content] of reference.pages) {
    await assertOrWrite(
      join(generatedRoot, filename),
      content,
      check,
      repositoryRoot,
    );
  }

  const expectedFiles = new Set(reference.pages.keys());
  const entries = await readdir(generatedRoot, { withFileTypes: true }).catch(
    (error: unknown) => {
      if (
        !check &&
        typeof error === "object" &&
        error !== null &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        return [];
      }
      throw error;
    },
  );
  for (const entry of entries) {
    if (
      !entry.isFile() ||
      !entry.name.endsWith(".mdx") ||
      expectedFiles.has(entry.name)
    ) {
      continue;
    }
    const stalePath = join(generatedRoot, entry.name);
    const source = await readFile(stalePath, "utf8");
    if (!source.includes(generatedMarker)) {
      throw new Error(`Refusing to remove non-generated page ${stalePath}.`);
    }
    if (check) {
      throw new Error(
        `${relative(repositoryRoot, stalePath)} is stale; run pnpm docs:sdk.`,
      );
    }
    await unlink(stalePath);
  }

  const docs = JSON.parse(await readFile(docsConfigPath, "utf8")) as DocsConfig;
  const sdkGroup = docs.navigation.find(
    (group) => group.group === "SDK Reference",
  );
  if (sdkGroup === undefined) {
    throw new Error("docs.json is missing the SDK Reference group.");
  }
  const authoredPages = [
    "sdk/typescript/client",
    "sdk/typescript/tools-get",
    "sdk/typescript/tools-search",
    "sdk/typescript/tools-execute",
    "sdk/typescript/connections",
    "sdk/typescript/executions",
    "sdk/typescript/errors",
  ];
  sdkGroup.pages = sdkNavigation(authoredPages, reference.navigation);
  await assertOrWrite(
    docsConfigPath,
    `${JSON.stringify(docs, null, 2)}\n`,
    check,
    repositoryRoot,
  );
  return reference;
}

async function main(): Promise<void> {
  const unknownArguments = process.argv
    .slice(2)
    .filter((argument) => argument !== "--check");
  if (unknownArguments.length > 0) {
    throw new Error(`Unknown arguments: ${unknownArguments.join(", ")}`);
  }
  const check = process.argv.includes("--check");
  const reference = await generateSdkDocs({ check });
  console.log(
    `${check ? "Verified" : "Generated"} ${reference.pages.size} SDK reference pages (checksum ${reference.checksum}).`,
  );
}

const invokedPath = process.argv[1];
if (
  invokedPath !== undefined &&
  resolve(invokedPath).split(sep).join("/") ===
    fileURLToPath(import.meta.url)
      .split(sep)
      .join("/")
) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
